spring:
  application:
    name: movie-booking-system
  datasource:
    #url: jdbc:mysql://localhost:3306/movie_booking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
    url: ${DB_URL}
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 10000
      idle-timeout: 300000
        # Maximum lifetime of a connection in the pool in milliseconds
      max-lifetime: 1800000
      pool-name: HikariCP-SeatBookingPool

  rabbitmq:
    addresses: ${RABBITMQ_URL}





  jpa:
    hibernate:
      ddl-auto: update



    show-sql: true

    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        generate_statistics: true
  mvc:
    async:
      request-timeout: 10000ms
  data:
    redis:
          url:${REDIS_URL}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
server:
  port: 8080
  tomcat:
    threads:
      max: 400
      min-spare: 50
    connection-timeout: 20000ms
    accept-count: 500

jwt:
  secret-key: ${SECRET_KEY}
  expiration: 86400000
email:
  service:
    url: ${EMAIL_SERVICE}